### ISSUE TITLE
Code compiles on Linux but won't work "free(): invalid pointer"

### ISSUE THREAD

**Issue by emanuele6** [jcs/sdorfehs#2]
Operating System: GNU/Linux
Distro: Arch Linux
Kernel version: Linux 4.19.69-1-lts
Hardware: Lenovo Thinkpad T420 i5, 8GB version

When I try to start `sdorfehs` from `.xinitrc` nothing happens: `sdorfehs` just prints `free(): invalid pointer` to stderr.

output of `startx > log 2> log2`:
* log:
```
output 0: size(1366, 768) pos(0, 0)
```
* log2:
```


X.Org X Server 1.20.5
X Protocol Version 11, Revision 0
Build Operating System: Linux Arch Linux
Current Operating System: Linux t420 4.19.69-1-lts #1 SMP Thu Aug 29 12:06:45 CEST 2019 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux-lts root=UUID=71a9975f-6c9f-44f0-8009-130055ef7a0e rw audit=0 loglevel=3 quiet
Build Date: 30 June 2019  09:52:01AM
 
Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Thu Sep 12 00:24:24 2019
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
> Internal error:   Could not resolve keysym XF86RotationLockToggle
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
> Internal error:   Could not resolve keysym XF86RotationLockToggle
Errors from xkbcomp are not fatal to the X server
[ 12/09/19 00:24:25.064 parse_config_libconfig WARN ] vsync option will take a boolean from now on. "opengl" is interpreted as "true" for compatibility, but this will sto
p working soon
[ 12/09/19 00:24:25.064 parse_config_libconfig WARN ] glx-swap-method has been deprecated since v6, your setting "undefined" should be removed.
free(): invalid pointer
xinit: connection to X server lost

waiting for X server to shut down urxvt: X connection to ':0' broken, unable to recover, exiting.
(II) Server terminated successfully (0). Closing log file.

```

**Comment by jcs** [comment]
Can you run `xterm` from `.xinitrc` instead of `sdorfehs`, and then run `gdb sdorfehs` and then `run` and see what it prints?

**Comment by emanuele6** [comment]
Sure thing:
```
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sdorfehs...
(No debugging symbols found in sdorfehs)
(gdb) run
Starting program: /usr/local/bin/sdorfehs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
free(): invalid size

Program received signal SIGABRT, Aborted.
0x00007ffff7cb0755 in raise () from /usr/lib/libc.so.6
(gdb) quit
A debugging session is active.

        Inferior 1 [process 93204] will be killed.

Quit anyway? (y or n) y


```

**Comment by jcs** [comment]
That's not very useful... is it not passing `-g` to `cc` when compiling?

**Comment by jcs** [comment]
I just did a quick installation of Arch and it compiled with `-g`, gdb was able to read debugging symbols, and it didn't crash.  Do you have anything in your sdorfehs config or is it the default?

**Comment by emanuele6** [comment]
No, I did not create any config file.

This is what you requested:
```
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/emanuele6/.apps/git/sdorfehs/sdorfehs...
(gdb) run
Starting program: /home/emanuele6/.apps/git/sdorfehs/sdorfehs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
free(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff7cb0755 in raise () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007ffff7cb0755 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7c9b851 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7cf2a38 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff7cf925a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff7cfa9cc in _int_free () from /usr/lib/libc.so.6
#5  0x000055555556a6ab in get_config_dir () at globals.c:572
#6  0x000055555555903a in bar_mkfifo () at sdorfehs.c:368
#7  main (argc=1, argv=0x7fffffffe978) at sdorfehs.c:368
(gdb) quit
A debugging session is active.

        Inferior 1 [process 95645] will be killed.

Quit anyway? (y or n) y
```

**Comment by jcs** [comment]
Can you try updating to a7b265a and see if that helps?

**Comment by emanuele6** [comment]
It fixed it, thanks.
